### ISSUE TITLE
FAQ is out of date

### ISSUE THREAD

**Issue by knighty** [knighty/fimfiction-issues#112]
Bunch of links need sorting and out dated info needs refreshed.

**Comment by sweetaibelle** [comment]
Offhand, the entry on banning someone from a group should be updated, and the entry about BBCode should probably point to the site guide for it, instead of CosmicAfro's old one. Also, two out of four emails under "Help, I've been banned" are for former staff members. 

I'm sure there's other outdated things, but those were the ones that stood out in a quick lookthrough...

**Comment by knighty** [comment]
Think I got the major ones, but will continue to add to later.
