### ISSUE TITLE
Poetry mode

### ISSUE THREAD

**Issue by marcus-downing** [knighty/fimfiction-issues#12]
The paragraph handling takes decisions of indentation and paragraph style out of the hands of authors, standardisation the way paragraphs are interpreted and giving readers the option to choose between _Double Spaced_, _Indented_ or _Both_. This is good for prose, as it saves authors from worrying about an issue that distracts them from writing and gives readers the freedom to enjoy stories as they wish.

However, there are some cases where an author need more fine control over layout: poetry, song lyrics, and any story where the layout is used to convey specific effect. In these cases an author needs control of:

- Where line breaks occur, so that verses / stanzas are clearly separated.
- Indentation, as a hint to rhyming schemes and reading flow

There are two ways to address this. The first is with a number of little bbcode tags such as `[br]` that allow an author to adjust layout. The second is with a single block level tag `[nolayout]...[/nolayout]`, within which standard paragraph rules don't apply and layout is up to the author. I favour the second approach, because its intent is more clear and it doesn't encourage abuse as much.

**Comment by TrickQuestion** [comment]
Didn't this get fixed with the addition of the new tags?

**Comment by marcus-downing** [comment]
I believe so, I need to test them before approving.

**Comment by marcus-downing** [comment]
Yes, this is fixed with [the addition](https://www.fimfiction.net/blog/741660/new-bbcode-tags) of the `[pre-line]` and `[indent]` tags.

**Comment by xaquseg** [comment]
Unicode whitespace (like em space) can also be used to indent individual lines. If you need exact alignment we have the `[pre]` tag as well, but that's limited to a monospaced font (because otherwise said alignment would be impossible).

Both of these solutions will wrap in what are probably undesirable ways, but there is no good solution to that problem, as the situations where you'd need to use either of these there isn't really a way you can wrap the text that doesn't cause problems. If using `[pre-line]` and/or `[indent]` is practical, it's the better solution.

**Comment by marcus-downing** [comment]
The new `[indent]` tag causes all lines of a block to be intented, not just the first. That means lines that wrap on a smaller device at least wrap to a suitable place. I'm satisfied that it's as good as it could be.

**Comment by marcus-downing** [comment]
An argument could be made for a `[nowrap]` tag, but I suspect it would cause more problems than it solved.
