### ISSUE TITLE
science fantasy tag

### ISSUE THREAD

**Issue by DagonMDragoon** [knighty/fimfiction-issues#281]
Can we get a science fantasy tag please

**Comment by ocalhoun6** [comment]
If you had a [fantasy] tag, you could just use it in combination with the existing [science fiction] tag.

That said, I'm not sure about the usefulness of a fantasy tag in an MLP fandom, since canon MLP already includes a lot of fantasy elements. (I mean, you could have a unicorn fighting a dragon with magic, and that could just be a normal MLP episode.) I'm not sure what elements you'd be adding to a story to make it more 'fantasy' than MLP itself already is.

**Comment by sweetaibelle** [comment]
A unicorn fighting a dragon with magic sounds like what you do if you're bored on the weekend, and Spike's also feeling bored...

**Comment by DagonMDragoon** [comment]
@ocalhoun6 that takes up two of the three tag slots and does not convey quiet the same meaning. As for the fantasy tag itself it can be used in conjunction with the crossover tag when the crossover is a fantasy setting like D&D's Dragon Lance or when you are writing a story in a more traditional fantasy setting then cannon allows for.

**Comment by ocalhoun6** [comment]
> that takes up two of the three tag slots

All the more reason to avoid unnecessary proliferation of tags...

> in a more traditional fantasy setting then cannon allows for

What fantasy setting elements does canon not allow for?

**Comment by knighty** [comment]
I think Fantasy could be useful down the line but in the context of MLP it's implied anyway.
