### ISSUE TITLE
"Mark All Read" button on the notifications page does not function.

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#5]
The MAR button _on the notifications page_ does not work properly. This has always been a problem to an extent: previously, it didn't work for certain kinds of notifications (such as group requests), but now it doesn't seem to do anything.

As with Fimfiction 3.0, the MAR button in the dropdown for notifications works just fine. It's only the one on the notifications page that fails.

**Comment by GB-92** [comment]
I cannot do anything to notifications at all. As mentioned above, the Mark All Read button does nothing. However, trying to individually mark each notification as "read" does nothing as well. No matter where I click, no matter if it's on the notifications page or on the dropdown menu, nothing happens. I've had notifications sitting there since the site was updated.

**Comment by knighty** [comment]
Fixed
